import React, { useState, useEffect } from 'react';
import { X, Save, Mail, Trash2, Plus } from 'lucide-react';
import { fetchEmailSettings, saveEmailSettings } from '../services/firebase';
import { useSettings } from '../contexts/SettingsContext';

interface EmailSettingsProps {
    onClose: () => void;
}

const EmailSettings: React.FC<EmailSettingsProps> = ({ onClose }) => {
    const { t } = useSettings();
    const [emails, setEmails] = useState<string[]>([]);
    const [newEmail, setNewEmail] = useState('');
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');

    useEffect(() => {
        const load = async () => {
            try {
                const data = await fetchEmailSettings();
                setEmails(data || []);
            } catch (err: any) {
                setError(err.message || 'Error loading emails');
            } finally {
                setLoading(false);
            }
        };
        load();
    }, []);

    const handleAdd = () => {
        if (!newEmail || !newEmail.includes('@')) {
            setError('Please enter a valid email address');
            return;
        }
        if (emails.includes(newEmail)) {
            setError('Email already exists');
            return;
        }
        setEmails([...emails, newEmail.toLowerCase()]);
        setNewEmail('');
        setError('');
    };

    const handleRemove = (email: string) => {
        setEmails(emails.filter(e => e !== email));
        setError('');
    };

    const handleSave = async () => {
        setSaving(true);
        setError('');
        setSuccess('');
        try {
            await saveEmailSettings(emails);
            setSuccess('Email settings saved successfully!');
            setTimeout(() => {
                onClose();
            }, 1500);
        } catch (err: any) {
            setError(err.message || 'Error saving emails');
        } finally {
            setSaving(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4" dir="auto">
            <div className="bg-white dark:bg-[#191E26] rounded-3xl shadow-2xl w-full max-w-md overflow-hidden animate-scale-in border border-gray-100 dark:border-gray-800">
                <div className="bg-[#232F3E] p-6 text-white flex justify-between items-center">
                    <h2 className="text-xl font-black flex items-center gap-3">
                        <Mail className="w-6 h-6 text-[#FF9900]" />
                        Automated Daily Reports (Emails)
                    </h2>
                    <button onClick={onClose} className="hover:bg-white/10 p-2 rounded-full transition-colors text-gray-300 hover:text-white">
                        <X className="w-5 h-5" />
                    </button>
                </div>
                
                <div className="p-6">
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
                        Configure the email addresses that will receive the automated daily summary reports generated by Firebase Functions.
                    </p>

                    {error && (
                        <div className="mb-4 p-3 bg-red-50 text-red-600 rounded-xl text-sm border border-red-100 flex items-start gap-2">
                            <span className="mt-0.5">⚠️</span> {error}
                        </div>
                    )}
                    {success && (
                        <div className="mb-4 p-3 bg-emerald-50 text-emerald-600 rounded-xl text-sm border border-emerald-100 flex items-start gap-2">
                            <span className="mt-0.5">✅</span> {success}
                        </div>
                    )}

                    <div className="flex gap-2 mb-6">
                        <input 
                            type="email" 
                            value={newEmail}
                            onChange={(e) => setNewEmail(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleAdd()}
                            placeholder="Enter email address"
                            className="flex-1 bg-gray-50 dark:bg-[#232F3E] border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white rounded-xl px-4 py-2 focus:ring-2 focus:ring-[#FF9900] focus:border-transparent outline-none transition-all"
                        />
                        <button 
                            onClick={handleAdd}
                            className="bg-[#232F3E] dark:bg-[#37475A] hover:bg-[#FF9900] text-white px-4 py-2 rounded-xl transition-colors flex items-center justify-center shadow-md"
                        >
                            <Plus className="w-5 h-5" />
                        </button>
                    </div>

                    <div className="bg-gray-50 dark:bg-[#232F3E] rounded-xl border border-gray-200 dark:border-gray-700 min-h-[150px] max-h-[250px] overflow-y-auto mb-6">
                        {loading ? (
                            <div className="flex items-center justify-center h-full p-8 text-gray-400">Loading...</div>
                        ) : emails.length === 0 ? (
                            <div className="flex items-center justify-center h-full p-8 text-gray-400 text-sm text-center">
                                No email addresses configured yet.<br/>Add one above.
                            </div>
                        ) : (
                            <ul className="divide-y divide-gray-200 dark:divide-gray-700">
                                {emails.map((email, idx) => (
                                    <li key={idx} className="flex justify-between items-center p-3 hover:bg-white dark:hover:bg-[#191E26] transition-colors">
                                        <span className="text-gray-800 dark:text-gray-200 font-medium truncate pr-4">{email}</span>
                                        <button 
                                            onClick={() => handleRemove(email)}
                                            className="text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 p-2 rounded-lg transition-colors flex-shrink-0"
                                        >
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>

                    <div className="flex justify-end gap-3 pt-4 border-t border-gray-100 dark:border-gray-800">
                        <button 
                            onClick={onClose}
                            className="px-5 py-2.5 text-gray-600 dark:text-gray-300 font-bold hover:bg-gray-100 dark:hover:bg-gray-800 rounded-xl transition-colors"
                        >
                            Cancel
                        </button>
                        <button 
                            onClick={handleSave}
                            disabled={saving}
                            className="bg-[#FF9900] hover:bg-[#F3A847] text-white px-6 py-2.5 rounded-xl font-bold flex items-center gap-2 shadow-lg shadow-orange-500/30 transition-all disabled:opacity-50"
                        >
                            {saving ? 'Saving...' : (
                                <>
                                    <Save className="w-5 h-5" />
                                    Save Configuration
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default EmailSettings;
